openapi: 3.0.0
info:
  title: api-auth
  version: 1.0.0
  description: Auth API for handling authentication
  contact:
    email: developer@albertinvent.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "http://localhost:9001"
    description: Local server
  - url: "http://127.0.0.1:9001/cloud-trackrapp/us-central1/auth"
    description: Dev server
paths:
  /health:
    get:
      summary: Health Check
      operationId: health
      tags:
        - Health Check
      responses:
        "200":
          description: successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Health"
components:
  schemas:
    Health:
      properties:
        status:
          type: string
          example: ok
        ts:
          type: integer
