version: 2
jobs:
  run-prebuild-installation:
    docker:
    - image: cimg/node:lts
    resource_class: small
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - run:
        name: Install dependencies
        command: npm install
    - persist_to_workspace:
        root: .
        paths:
        - '*'
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
  run-unit-test:
    docker:
    - image: cimg/node:lts
    resource_class: small
    steps:
    - checkout
    - run:
        name: Run tests
        command: npm test
  deploy:
    docker:
    - image: cimg/node:lts
    resource_class: small
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - run:
        name: Install Firebase CLI
        command: npm install firebase-tools
    - run:
        name: Deploy to Firebase
        command: firebase deploy --only functions,firestore --token $FIREBASE_TOKEN
workflows:
  test-build-n-deploy-image:
    jobs:
    - run-prebuild-installation
    - run-unit-test:
        requires:
        - run-prebuild-installation
    - deploy:
        requires:
        - run-prebuild-installation
  version: 2
